#!/usr/bin/env bash
set -euo pipefail

OWNER="integrio-intropy"
REPO="intropy-cli"
TAP_OWNER="integrio-intropy"
TAP_REPO="homebrew-tap"
BINARY="intropy"
DIST_DIR="${DIST_DIR:-dist}"
DRY_RUN=0
TAG="${GITHUB_REF_NAME:-}"

usage() {
  cat <<'USAGE'
usage: update-homebrew-formula.sh [--dry-run] [--tag <tag>]

Writes the Intropy Homebrew formula from GoReleaser artifacts in dist/.
USAGE
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    --dry-run)
      DRY_RUN=1
      shift
      ;;
    --tag)
      TAG="$2"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "unknown option: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

if [ -z "$TAG" ]; then
  echo "GITHUB_REF_NAME or --tag is required" >&2
  exit 1
fi

VERSION="${TAG#v}"
CHECKSUMS="${DIST_DIR}/checksums.txt"

if [ ! -f "$CHECKSUMS" ]; then
  echo "checksums file not found: $CHECKSUMS" >&2
  exit 1
fi

checksum_for() {
  local artifact="$1"
  local checksum
  checksum=$(awk -v artifact="$artifact" '$2 == artifact { print $1 }' "$CHECKSUMS")
  if [ -z "$checksum" ]; then
    echo "checksum not found for $artifact" >&2
    exit 1
  fi
  printf '%s' "$checksum"
}

artifact_name() {
  local os="$1"
  local arch="$2"
  printf '%s_%s_%s_%s.tar.gz' "$BINARY" "$VERSION" "$os" "$arch"
}

url_for() {
  local artifact="$1"
  printf 'https://github.com/%s/%s/releases/download/%s/%s' "$OWNER" "$REPO" "$TAG" "$artifact"
}

DARWIN_AMD64="$(artifact_name darwin amd64)"
DARWIN_ARM64="$(artifact_name darwin arm64)"
LINUX_AMD64="$(artifact_name linux amd64)"
LINUX_ARM64="$(artifact_name linux arm64)"

FORMULA_FILE="$(mktemp)"
WORKDIR=""
trap 'rm -rf "$WORKDIR" "$FORMULA_FILE"' EXIT

cat > "$FORMULA_FILE" <<FORMULA
# frozen_string_literal: true

# This file was generated by the intropy release workflow. DO NOT EDIT.
class Intropy < Formula
  desc "CLI for Intropy integrations"
  homepage "https://github.com/${OWNER}/${REPO}"
  version "${VERSION}"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "$(url_for "$DARWIN_AMD64")"
      sha256 "$(checksum_for "$DARWIN_AMD64")"
    end

    if Hardware::CPU.arm?
      url "$(url_for "$DARWIN_ARM64")"
      sha256 "$(checksum_for "$DARWIN_ARM64")"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "$(url_for "$LINUX_AMD64")"
      sha256 "$(checksum_for "$LINUX_AMD64")"
    end

    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "$(url_for "$LINUX_ARM64")"
      sha256 "$(checksum_for "$LINUX_ARM64")"
    end
  end

  def install
    bin.install "${BINARY}"
    generate_completions_from_executable(bin/"${BINARY}", "completion")
  end

  test do
    system "#{bin}/${BINARY}", "version"
  end
end
FORMULA

ruby -c "$FORMULA_FILE" >/dev/null

if [ "$DRY_RUN" -eq 1 ]; then
  cat "$FORMULA_FILE"
  exit 0
fi

if [ -z "${TAP_GITHUB_TOKEN:-}" ]; then
  echo "TAP_GITHUB_TOKEN is required" >&2
  exit 1
fi

WORKDIR="$(mktemp -d)"

TAP_URL="https://x-access-token:${TAP_GITHUB_TOKEN}@github.com/${TAP_OWNER}/${TAP_REPO}.git"
git clone --depth 1 "$TAP_URL" "$WORKDIR/tap"

mkdir -p "$WORKDIR/tap/Formula"
cp "$FORMULA_FILE" "$WORKDIR/tap/Formula/intropy.rb"

if [ -f "$WORKDIR/tap/Casks/intropy.rb" ]; then
  git -C "$WORKDIR/tap" rm -f Casks/intropy.rb
fi

git -C "$WORKDIR/tap" add Formula/intropy.rb

if git -C "$WORKDIR/tap" diff --cached --quiet; then
  echo "homebrew formula already up to date"
  exit 0
fi

BASE_BRANCH=$(git -C "$WORKDIR/tap" remote show origin | awk '/HEAD branch/ { print $NF }')
if [ -z "$BASE_BRANCH" ]; then
  BASE_BRANCH="main"
fi

BRANCH="release/intropy-${VERSION}"
git -C "$WORKDIR/tap" checkout -b "$BRANCH"
git -C "$WORKDIR/tap" config user.name "github-actions[bot]"
git -C "$WORKDIR/tap" config user.email "41898282+github-actions[bot]@users.noreply.github.com"
git -C "$WORKDIR/tap" commit -m "Brew formula update for intropy version ${TAG}"
git -C "$WORKDIR/tap" push --force-with-lease origin "HEAD:${BRANCH}"

MANUAL_PR_URL="https://github.com/${TAP_OWNER}/${TAP_REPO}/pull/new/${BRANCH}"

if EXISTING_PR=$(GH_TOKEN="$TAP_GITHUB_TOKEN" gh pr list \
  --repo "${TAP_OWNER}/${TAP_REPO}" \
  --head "$BRANCH" \
  --json url \
  --jq '.[0].url'); then
  if [ -n "$EXISTING_PR" ]; then
    echo "$EXISTING_PR"
    exit 0
  fi
fi

if GH_TOKEN="$TAP_GITHUB_TOKEN" gh pr create \
  --repo "${TAP_OWNER}/${TAP_REPO}" \
  --base "$BASE_BRANCH" \
  --head "$BRANCH" \
  --title "Brew formula update for intropy version ${TAG}" \
  --body "Updates the intropy Homebrew formula for ${TAG}."; then
  exit 0
fi

echo "homebrew formula branch pushed, but pull request creation failed" >&2
echo "open the tap PR manually: ${MANUAL_PR_URL}" >&2

if [ -n "${GITHUB_STEP_SUMMARY:-}" ]; then
  {
    echo "## Homebrew formula PR"
    echo
    echo "The formula branch was pushed, but the workflow token could not create the pull request."
    echo
    echo "Open it manually: ${MANUAL_PR_URL}"
  } >> "$GITHUB_STEP_SUMMARY"
fi
