// Material Symbols (outlined, weight 400) as React components via svgr.
// Import icons here so the rest of the app has one place to see which
// glyphs are in use; each import adds only that SVG to the bundle.
export { default as CategoryIcon } from '@material-symbols/svg-400/outlined/category.svg?react'
export { default as ChevronRightIcon } from '@material-symbols/svg-400/outlined/chevron_right.svg?react'
export { default as CloudIcon } from '@material-symbols/svg-400/outlined/cloud.svg?react'
export { default as CycleIcon } from '@material-symbols/svg-400/outlined/cycle.svg?react'
export { default as DarkModeIcon } from '@material-symbols/svg-400/outlined/dark_mode.svg?react'
export { default as DatabaseIcon } from '@material-symbols/svg-400/outlined/database.svg?react'
export { default as DescriptionIcon } from '@material-symbols/svg-400/outlined/description.svg?react'
export { default as DomainIcon } from '@material-symbols/svg-400/outlined/domain.svg?react'
export { default as ExpandMoreIcon } from '@material-symbols/svg-400/outlined/keyboard_arrow_down.svg?react'
export { default as ExtensionIcon } from '@material-symbols/svg-400/outlined/extension.svg?react'
export { default as HardDriveIcon } from '@material-symbols/svg-400/outlined/hard_drive.svg?react'
export { default as HubIcon } from '@material-symbols/svg-400/outlined/hub.svg?react'
export { default as InputIcon } from '@material-symbols/svg-400/outlined/input.svg?react'
export { default as LightModeIcon } from '@material-symbols/svg-400/outlined/light_mode.svg?react'
export { default as SystemThemeIcon } from '@material-symbols/svg-400/outlined/brightness_auto.svg?react'
export { default as LeftPanelCloseIcon } from '@material-symbols/svg-400/outlined/left_panel_close.svg?react'
export { default as LeftPanelOpenIcon } from '@material-symbols/svg-400/outlined/left_panel_open.svg?react'
export { default as MemoryIcon } from '@material-symbols/svg-400/outlined/memory.svg?react'
export { default as OutputIcon } from '@material-symbols/svg-400/outlined/output.svg?react'
export { default as RouteIcon } from '@material-symbols/svg-400/outlined/route.svg?react'
export { default as SearchIcon } from '@material-symbols/svg-400/outlined/search.svg?react'
export { default as SyncAltIcon } from '@material-symbols/svg-400/outlined/sync_alt.svg?react'
export { default as TuneIcon } from '@material-symbols/svg-400/outlined/tune.svg?react'
