package deploy

import (
	"bytes"
	"context"
	"fmt"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"slices"
	"strings"

	"github.com/integrio-intropy/intropy-cli/internal/command"
	"github.com/integrio-intropy/intropy-cli/internal/git"
	"github.com/integrio-intropy/intropy-cli/internal/kustomize"
	"github.com/integrio-intropy/intropy-cli/internal/template"
	"gopkg.in/yaml.v3"
)

// kustomizeBuild is the seam unit tests replace to avoid the kustomize
// binary; production wires kustomize.Client.Build.
var kustomizeBuild = func(ctx context.Context, runner command.Runner, dir string) ([]byte, error) {
	return kustomize.Client{Runner: runner}.Build(ctx, dir)
}

// localEnv is the only environment a local render knows. It names the overlay
// the templates ship for the local cluster and lands in .gitops.env.
const localEnv = "local"

// localRegistry is the placeholder registry a local render reports. Every
// Deployment image is overridden by the root kustomization's images[] entries,
// so the rendered registry is never pulled from.
const localRegistry = "dev"

// localImageTag is the conventional tag the k3s scripts build and load
// component images under.
const localImageTag = "dev"

// localExclusionReason is the when-condition appended to every spec.files rule
// for a local render. It is always false, which excludes exactly the files the
// template declared conditional — repo metadata like component.yaml — while
// leaving unconditional skeleton files (the manifests) untouched. The
// exclusion list itself is the templates' spec.files, kept in sync with the
// fixture-contract doc over there.
const localExclusionReason = "repo metadata; a local render emits manifests only"

// LocalOptions configures Local.
//
// There are no value files and no --set, deliberately: every fact the
// templates need is derived (topology, scaffold records, local constants,
// .intropy/local.yaml), and an escape hatch would let one developer's render
// diverge from the team's checked-in state. There is no Environment either —
// a local render is always the local overlay.
type LocalOptions struct {
	// System names the system to render. It selects which system host to read
	// the topology from when a workspace holds several. Empty means the only
	// host in the workspace, named by whatever its topology declares.
	System string

	// Namespace is the target namespace in the emitted manifests. Empty
	// defaults to the system name.
	Namespace string

	// Images overrides image references, repeatable. "<component>=<name:tag>"
	// overrides one component's entry; ":<tag>" (leading colon) retags every
	// component — the release-candidate flow.
	Images []string

	// NoInput fails instead of prompting when a connector has no recorded
	// binding or a template parameter has no derivable value.
	NoInput bool

	// TemplateVersion pins the template library release.
	TemplateVersion string

	// TopologyFile reads the record from a file instead of running the host's
	// graph verb; "-" reads stdin. Internal test seam — not exposed as a CLI flag.
	TopologyFile string

	// SourceDir is where system hosts and scaffold records are discovered, and
	// where .intropy/local.yaml lives. Internal test seam — the CLI always
	// runs from the workspace root.
	SourceDir string

	// Runner drives the kustomize binary.
	Runner command.Runner

	UserAgent string

	// Owner and Repo select the template library; zero values target the
	// official library. GitHubBaseURL is a test-only seam.
	Owner         string
	Repo          string
	GitHubBaseURL string
	HTTP          *http.Client

	Stdin  io.Reader
	Stdout io.Writer
	Stderr io.Writer
}

func (o *LocalOptions) applyDefaults() {
	if o.Runner == nil {
		o.Runner = git.DefaultRunner()
	}
	if o.SourceDir == "" {
		o.SourceDir = "."
	}
	if o.UserAgent == "" {
		o.UserAgent = "intropy-cli"
	}
	if o.Stdin == nil {
		o.Stdin = os.Stdin
	}
	if o.Stdout == nil {
		o.Stdout = os.Stdout
	}
	if o.Stderr == nil {
		o.Stderr = os.Stderr
	}
}

// localFacts is what newInitFacts becomes when there is no GitOps repository
// to derive from: the environments, registry and platform are constants of the
// local cluster the k3s scripts install, and the domain is omitted entirely.
type localFacts struct {
	System    string
	Model     InitModel
	Scaffolds map[string]template.ScaffoldEntry
}

func newLocalFacts(opts LocalOptions, found discoveredTopology) (localFacts, error) {
	topo := found.Topology

	system := opts.System
	if system == "" {
		system = topo.System
	}
	if system == "" {
		return localFacts{}, fmt.Errorf("the topology record names no system; pass --system")
	}
	if err := assertPathSegment("--system", system); err != nil {
		return localFacts{}, err
	}

	model := newInitModel(topo, found.Scaffolds)
	for _, c := range model.Components {
		// From the topology record, which is generated by a build this CLI does
		// not own: a name with a separator in it would render into a directory
		// of its own choosing.
		if err := assertPathSegment("component name", c.Name); err != nil {
			return localFacts{}, err
		}
		if c.Dir == "" {
			fmt.Fprintf(opts.Stderr, "warning: %s has no scaffold record under the workspace root; its manifests will be generated without an appId or sourcePaths\n", c.Name)
		}
	}

	return localFacts{
		System:    system,
		Model:     model,
		Scaffolds: matchScaffolds(topo.Components, found.Scaffolds),
	}, nil
}

// gitopsMap is the reserved .gitops map for a local render. Fields that have
// no local meaning — domain, the ArgoCD app namespace — are present but empty,
// and the fixture contract forbids the local overlay's skeletons from
// referencing them. registry is the placeholder the root kustomization's
// images[] entries make irrelevant.
func (f localFacts) gitopsMap(component string) map[string]any {
	return map[string]any{
		"domain":             "",
		"system":             f.System,
		"component":          component,
		"env":                localEnv,
		"host":               HostDirName,
		"registry":           localRegistry,
		"argocdAppNamespace": "",
		"environments":       []string{localEnv},
		"platform": map[string]any{
			"provider":    "kubernetes",
			"pubsub":      "redis",
			"secretStore": "kubernetes",
		},
	}
}

// scaffoldValues mirrors initFacts.scaffoldValues: an empty map rather than a
// missing key, so a skeleton reading .scaffold.x never fails on a missing record.
func (f localFacts) scaffoldValues(component string) map[string]any {
	if s, ok := f.Scaffolds[component]; ok && s.Values != nil {
		return s.Values
	}
	return map[string]any{}
}

// imageOverride is one parsed --image entry: a per-component newName/newTag
// pair, or a global newTag when Component is empty.
type imageOverride struct {
	Component string
	NewName   string
	NewTag    string
}

// parseImageOverrides parses the --image grammar: "<component>=<name:tag>" for
// one component, ":<tag>" for all of them. Anything else is a usage error
// showing both forms.
func parseImageOverrides(args []string) ([]imageOverride, error) {
	var out []imageOverride
	for _, arg := range args {
		if strings.HasPrefix(arg, ":") {
			tag := strings.TrimPrefix(arg, ":")
			if tag == "" || strings.ContainsAny(tag, "=:") {
				return nil, invalidImageOverride(arg)
			}
			out = append(out, imageOverride{NewTag: tag})
			continue
		}
		component, ref, found := strings.Cut(arg, "=")
		name, tag, tagged := strings.Cut(ref, ":")
		if !found || component == "" || !tagged || name == "" || tag == "" || strings.Contains(tag, ":") {
			return nil, invalidImageOverride(arg)
		}
		out = append(out, imageOverride{Component: component, NewName: name, NewTag: tag})
	}
	return out, nil
}

func invalidImageOverride(arg string) error {
	return fmt.Errorf("invalid --image %q\nvalid forms: --image <component>=<name:tag> to override one component, --image :<tag> to retag every component", arg)
}

// Local renders a system's deployable manifests for the local development
// cluster and writes the multi-document YAML to opts.Stdout.
//
// The render is unconditional: fixture servers are always installed on the
// local cluster by the k3s scripts, so the only decision this command makes is
// which fixture each connector binds to, recorded in .intropy/local.yaml.
// Nothing else is written — no git, no branches — and the command never
// inspects the cluster: it renders, kubectl applies, a missing cluster fails
// at apply time with kubectl's own error.
func Local(ctx context.Context, opts LocalOptions) error {
	opts.applyDefaults()

	overrides, err := parseImageOverrides(opts.Images)
	if err != nil {
		return err
	}

	found, err := resolveInitTopology(ctx, InitOptions{
		System:       opts.System,
		TopologyFile: opts.TopologyFile,
		SourceDir:    opts.SourceDir,
		Stdin:        opts.Stdin,
		Stderr:       opts.Stderr,
	})
	if err != nil {
		return err
	}

	facts, err := newLocalFacts(opts, found)
	if err != nil {
		return err
	}
	namespace := opts.Namespace
	if namespace == "" {
		namespace = facts.System
	}

	lib, err := template.FetchLibrary(ctx, template.LibraryOptions{
		Version:       opts.TemplateVersion,
		HTTP:          opts.HTTP,
		UserAgent:     opts.UserAgent,
		Stderr:        opts.Stderr,
		Owner:         opts.Owner,
		Repo:          opts.Repo,
		GitHubBaseURL: opts.GitHubBaseURL,
	})
	if err != nil {
		return err
	}
	defer lib.Close()

	// The catalog comes from the fetched release, so the menu, the validation
	// and the rendered binding skeletons can never drift apart.
	catalog, err := fixtureCatalog(lib)
	if err != nil {
		return err
	}

	bindings, err := resolveConnectorBindings(opts, facts, catalog)
	if err != nil {
		return err
	}

	staging, err := os.MkdirTemp("", "intropy-int-local-*")
	if err != nil {
		return fmt.Errorf("create staging directory: %w", err)
	}
	defer os.RemoveAll(staging)

	fmt.Fprintf(opts.Stderr, "rendering %s for local\n", facts.System)
	if err := renderLocal(opts, facts, bindings, lib, staging); err != nil {
		return err
	}

	images, err := localImageEntries(facts, overrides)
	if err != nil {
		return err
	}
	if err := writeLocalRootKustomization(staging, namespace, facts, images); err != nil {
		return err
	}

	built, err := kustomizeBuild(ctx, opts.Runner, staging)
	if err != nil {
		return err
	}
	if err := assertAllImagesTagged(built); err != nil {
		return err
	}
	if _, err := opts.Stdout.Write(built); err != nil {
		return fmt.Errorf("write manifests: %w", err)
	}
	return nil
}

// fixtureCatalog reads the closed fixture catalog from the fetched
// deploy-component template. A release without one cannot render bindings, so
// it is a hard error naming the release rather than a menu with no choices.
func fixtureCatalog(lib *template.Library) ([]string, error) {
	tmpl, _, err := lib.Open(TemplateDeployComponent)
	if err != nil {
		return nil, err
	}
	if tmpl.Spec.Local == nil || len(tmpl.Spec.Local.Fixtures) == 0 {
		return nil, fmt.Errorf("%s declares no fixture catalog (spec.local.fixtures on %s)\nuse --template-version to pin a library release that ships one", lib.Ref(), TemplateDeployComponent)
	}
	return tmpl.Spec.Local.Fixtures, nil
}

// resolveConnectorBindings loads the recorded bindings, prompts for the
// unbound ones against the fetched catalog, notes stale entries, and writes
// the file back only if an answer changed.
func resolveConnectorBindings(opts LocalOptions, facts localFacts, catalog []string) (map[string]string, error) {
	path := localConfigPath(opts.SourceDir)
	cfg, err := loadLocalConfig(path)
	if err != nil {
		return nil, err
	}

	// NewMenuPrompter rather than SelectPrompter: the connector question is
	// answered from piped stdin in tests and scripts too, and --no-input is
	// still what turns prompting off. The answer is persisted to a checked-in
	// file, so a piped answer is as reviewable as a typed one.
	var prompter *template.MenuPrompter
	if !opts.NoInput {
		prompter = template.NewMenuPrompter(opts.Stdin, opts.Stderr)
	}
	bindings := map[string]string{}
	changed := false
	for _, conn := range facts.Model.Connectors {
		choice, recorded := cfg.Bindings[conn.Name]
		if recorded {
			if !slices.Contains(catalog, choice) {
				return nil, fmt.Errorf("connector %s is bound to %q in %s, which %s does not offer; the catalog is: %s\nedit the file, or delete the entry to be asked again",
					conn.Name, choice, path, TemplateDeployComponent, strings.Join(catalog, ", "))
			}
			bindings[conn.Name] = choice
			continue
		}
		if prompter == nil {
			return nil, fmt.Errorf("connector %s has no local binding in %s\nrun 'intropy int local %s' interactively, or add it to the file",
				conn.Name, path, facts.System)
		}
		heading := fmt.Sprintf("connector %s (external system %s) — which binding?", conn.Name, conn.ExternalSystem)
		choice, err := prompter.Select(heading, catalog)
		if err != nil {
			return nil, fmt.Errorf("read binding for connector %s: %w", conn.Name, err)
		}
		bindings[conn.Name] = choice
		changed = true
	}
	for name := range cfg.Bindings {
		if !slices.ContainsFunc(facts.Model.Connectors, func(c InitConnector) bool { return c.Name == name }) {
			fmt.Fprintf(opts.Stderr, "note: local.yaml binds %s, which the topology no longer declares\n", name)
		}
	}

	if !changed {
		return bindings, nil
	}
	merged := map[string]string{}
	for k, v := range cfg.Bindings {
		merged[k] = v
	}
	for k, v := range bindings {
		merged[k] = v
	}
	if err := saveLocalConfig(path, localConfig{Bindings: merged}); err != nil {
		return nil, err
	}
	fmt.Fprintf(opts.Stderr, "recorded local bindings in %s\n", path)
	return bindings, nil
}

// renderLocal renders the host template once and the component template once
// per component, into a flat staging tree: no domain or system segment,
// because the temp root already holds exactly one system.
func renderLocal(opts LocalOptions, facts localFacts, bindings map[string]string, lib *template.Library, staging string) error {
	if err := renderLocalOne(opts, facts, bindings, lib, TemplateDeployHost, HostDirName, nil, staging); err != nil {
		return err
	}
	for _, c := range facts.Model.Components {
		comp := c
		if err := renderLocalOne(opts, facts, bindings, lib, TemplateDeployComponent, c.Name, &comp, staging); err != nil {
			return err
		}
	}
	return nil
}

// renderLocalOne renders one unit for the local environment. Unlike deploy
// init there is exactly one environment, so no per-env pass and no
// mergeRendered: the render lands in the staged tree directly.
func renderLocalOne(opts LocalOptions, facts localFacts, bindings map[string]string, lib *template.Library, templateName, dirName string, comp *InitComponent, staging string) error {
	tmpl, skeleton, err := lib.Open(templateName)
	if err != nil {
		return err
	}

	values, err := resolveLocalValues(opts, facts, bindings, tmpl, dirName, comp)
	if err != nil {
		return fmt.Errorf("%s for %s: %w", templateName, dirName, err)
	}

	dest := filepath.Join(staging, dirName)
	if err := os.MkdirAll(dest, 0o755); err != nil {
		return err
	}
	if err := template.RenderFiltered(skeleton, dest, values, localFileRules(tmpl.Spec.Files)); err != nil {
		return fmt.Errorf("render %s for %s: %w", templateName, dirName, err)
	}
	return nil
}

// resolveLocalValues layers the derived facts under a prompt for anything
// still missing, then injects the reserved structures. There are deliberately
// no value files and no --set: a local render must be reproducible from the
// team's checked-in state.
func resolveLocalValues(opts LocalOptions, facts localFacts, bindings map[string]string, tmpl *template.Template, dirName string, comp *InitComponent) (map[string]any, error) {
	base := seedDeclaredParams(tmpl, localSeeds(facts, dirName, comp))

	prompter := template.AutoPrompter(opts.Stdin, opts.Stderr, opts.NoInput)
	values, err := template.ResolveLayered(tmpl, base, nil, opts.Stdin, nil, prompter)
	if err != nil {
		return nil, err
	}

	model, err := facts.Model.asMap()
	if err != nil {
		return nil, err
	}
	local, err := toMap(localModel{Bindings: bindings})
	if err != nil {
		return nil, err
	}
	reserved := map[string]any{
		template.ReservedEnvKey:      localEnv,
		template.ReservedTopologyKey: model,
		template.ReservedGitopsKey:   facts.gitopsMap(dirName),
		template.ReservedLocalKey:    local,
	}
	if comp != nil {
		componentMap, err := toMap(comp)
		if err != nil {
			return nil, err
		}
		reserved[template.ReservedComponentKey] = componentMap
		reserved[template.ReservedScaffoldKey] = facts.scaffoldValues(comp.Name)
	}
	if err := template.InjectReserved(tmpl, values, reserved); err != nil {
		return nil, err
	}
	return values, nil
}

// localModel is the reserved .local structure: the per-connector fixture
// bindings decided by this command.
type localModel struct {
	Bindings map[string]string `json:"bindings"`
}

// localSeeds is initSeeds with local constants in place of the GitOps facts.
// Domain is omitted rather than blank, so a template that declares it required
// surfaces a prompt instead of silently rendering an empty tree segment.
func localSeeds(facts localFacts, dirName string, comp *InitComponent) map[string]any {
	seeds := map[string]any{
		"system":      facts.System,
		"hostName":    HostDirName,
		"registry":    localRegistry,
		"provider":    "kubernetes",
		"pubsub":      "redis",
		"secretStore": "kubernetes",
	}
	// Only when unambiguous, as on deploy init.
	if len(facts.Model.PubSubs) == 1 {
		seeds["pubsubName"] = facts.Model.PubSubs[0].Name
	}
	if comp != nil {
		seeds["name"] = comp.Name
		seeds["kind"] = comp.Kind
		seeds["appId"] = comp.AppID
		seeds["workload"] = comp.Workload
		if comp.Dir != "" {
			seeds["sourceDir"] = comp.Dir
		}
	} else {
		seeds["name"] = dirName
		seeds["appId"] = dirName
	}
	return seeds
}

// localFileRules narrows a template's file rules to manifests only: every
// declared rule is forced false, which excludes repo metadata such as
// component.yaml while leaving unconditional skeleton files alone.
func localFileRules(rules []template.FileRule) []template.FileRule {
	out := make([]template.FileRule, 0, len(rules))
	for _, r := range rules {
		out = append(out, template.FileRule{Path: r.Path, When: localExclusionReason})
	}
	return out
}

// localImageEntry is one images[] entry in the root kustomization.
type localImageEntry struct {
	Name    string `yaml:"name"`
	NewName string `yaml:"newName,omitempty"`
	NewTag  string `yaml:"newTag,omitempty"`
}

// localImageEntries resolves the images[] list: one entry per component, host
// excluded — the same fact requirePinnable encodes (the host is shared and
// declares no image). Each rendered reference is exactly the component name,
// the shape the fixture contract pins, so name matching cannot silently miss.
func localImageEntries(facts localFacts, overrides []imageOverride) ([]localImageEntry, error) {
	perComponent := map[string]imageOverride{}
	var global *imageOverride
	for _, o := range overrides {
		if o.Component == "" {
			g := o
			global = &g
			continue
		}
		perComponent[o.Component] = o
	}

	known := map[string]bool{}
	for _, c := range facts.Model.Components {
		known[c.Name] = true
	}
	var names []string
	for name := range perComponent {
		if !known[name] {
			names = append(names, name)
		}
	}
	if len(names) > 0 {
		slices.Sort(names)
		return nil, fmt.Errorf("--image names %s, which the topology does not declare as a component", strings.Join(names, ", "))
	}

	entries := make([]localImageEntry, 0, len(facts.Model.Components))
	for _, c := range facts.Model.Components {
		e := localImageEntry{Name: c.Name, NewTag: localImageTag}
		if o, ok := perComponent[c.Name]; ok {
			e.NewName = o.NewName
			e.NewTag = o.NewTag
		} else if global != nil {
			e.NewTag = global.NewTag
		}
		entries = append(entries, e)
	}
	return entries, nil
}

// localRootKustomization is the root kustomization the CLI writes after
// rendering: the only place namespace and the conventional image tags are
// applied, so templates stay namespace-agnostic and never hardcode a tag.
type localRootKustomization struct {
	APIVersion string            `yaml:"apiVersion"`
	Kind       string            `yaml:"kind"`
	Namespace  string            `yaml:"namespace"`
	Resources  []string          `yaml:"resources"`
	Images     []localImageEntry `yaml:"images,omitempty"`
}

func writeLocalRootKustomization(staging, namespace string, facts localFacts, images []localImageEntry) error {
	k := localRootKustomization{
		APIVersion: "kustomize.config.k8s.io/v1beta1",
		Kind:       "Kustomization",
		Namespace:  namespace,
		Resources:  []string{HostDirName + "/overlays/" + localEnv},
		Images:     images,
	}
	for _, c := range facts.Model.Components {
		k.Resources = append(k.Resources, c.Name+"/overlays/"+localEnv)
	}
	data, err := yaml.Marshal(k)
	if err != nil {
		return fmt.Errorf("encode root kustomization: %w", err)
	}
	if err := os.WriteFile(filepath.Join(staging, "kustomization.yaml"), data, 0o644); err != nil {
		return fmt.Errorf("write root kustomization: %w", err)
	}
	return nil
}

// assertAllImagesTagged is the belt-and-braces check against template drift:
// kustomize silently ignores an images[] entry whose name matches nothing, so
// a drifted image-reference convention would otherwise ship an unoverridden —
// and therefore untagged — image with no error until pull time.
func assertAllImagesTagged(manifest []byte) error {
	dec := yaml.NewDecoder(bytes.NewReader(manifest))
	for {
		var doc struct {
			Kind string `yaml:"kind"`
			Spec struct {
				Template struct {
					Spec struct {
						Containers []struct {
							Image string `yaml:"image"`
						} `yaml:"containers"`
					} `yaml:"spec"`
				} `yaml:"template"`
			} `yaml:"spec"`
		}
		if err := dec.Decode(&doc); err != nil {
			if err == io.EOF {
				return nil
			}
			return fmt.Errorf("parse rendered manifests: %w", err)
		}
		if doc.Kind != "Deployment" {
			continue
		}
		for _, c := range doc.Spec.Template.Spec.Containers {
			if c.Image == "" {
				continue
			}
			if !strings.Contains(c.Image, ":") && !strings.Contains(c.Image, "@") {
				return fmt.Errorf("a Deployment renders image %q without a tag\nkustomize overrides match on the exact rendered name; the local overlay's image reference convention (<component>:dev) may have drifted", c.Image)
			}
		}
	}
}
