//go:build integration

package deploy

import (
	"bytes"
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/integrio-intropy/intropy-cli/internal/gittest"
)

func createManifestFixtureOptions(t *testing.T, f initFixture, stdout, stderr *bytes.Buffer) CreateManifestOptions {
	t.Helper()
	return CreateManifestOptions{
		Environment:  "prod",
		Bindings:     []string{"erp=sftp", "price-master=http"},
		Domain:       "sales",
		SourceDir:    f.sourceDir,
		TopologyFile: f.topologyFile,
		CacheRoot:    f.cacheRoot,
		Stdout:       stdout,
		Stderr:       stderr,
		Source:       f.lib.Source(t),
	}
}

func TestCreateManifestsPublishesOnlyTheSelectedEnvironment(t *testing.T) {
	f := newInitFixture(t)
	var stdout, stderr bytes.Buffer
	if err := CreateManifests(context.Background(), createManifestFixtureOptions(t, f, &stdout, &stderr)); err != nil {
		t.Fatalf("CreateManifests: %v\nstderr: %s", err, stderr.String())
	}

	work := f.clone(t, "manifests-create/sales-distribution-prod")
	base := filepath.Join(work, "domains", "sales", "distribution", "extractor")
	if _, err := os.Stat(filepath.Join(base, "overlays", "prod", "kustomization.yaml")); err != nil {
		t.Fatalf("prod overlay: %v", err)
	}
	if got, err := filepath.Glob(filepath.Join(base, "overlays", "dev", "kustomization.yaml")); err != nil || len(got) != 0 {
		t.Errorf("dev overlay = %v, %v; create should render only prod", got, err)
	}
	body := readTreeFile(t, work, "domains/sales/distribution/extractor/component.yaml")
	if strings.Contains(body, "generated by intropy") {
		t.Error("created files must become normal editable GitOps source")
	}
}

func TestCreateManifestsPublishesEveryEnvironmentWhenUnspecified(t *testing.T) {
	f := newInitFixture(t)
	var stdout, stderr bytes.Buffer
	opts := createManifestFixtureOptions(t, f, &stdout, &stderr)
	opts.Environment = ""
	if err := CreateManifests(context.Background(), opts); err != nil {
		t.Fatalf("CreateManifests: %v\nstderr: %s", err, stderr.String())
	}

	work := f.clone(t, "manifests-create/sales-distribution-all")
	base := filepath.Join(work, "domains", "sales", "distribution", "extractor", "overlays")
	for _, env := range []string{"dev", "staging", "prod"} {
		if _, err := os.Stat(filepath.Join(base, env, "kustomization.yaml")); err != nil {
			t.Errorf("%s overlay: %v", env, err)
		}
	}
	log := gittest.Run(t, work, "log", "-1", "--format=%s")
	if !strings.Contains(log, " all files under sales") {
		t.Errorf("commit subject = %q", log)
	}
}

func TestCreateManifestsAcceptsExistingIdenticalFiles(t *testing.T) {
	f := newInitFixture(t)
	var firstOut, firstErr bytes.Buffer
	if err := CreateManifests(context.Background(), createManifestFixtureOptions(t, f, &firstOut, &firstErr)); err != nil {
		t.Fatalf("first CreateManifests: %v", err)
	}
	branch := "manifests-create/sales-distribution-prod"
	gittest.Run(t, f.gitopsOrigin, "merge", "--ff-only", branch)
	gittest.Run(t, f.gitopsOrigin, "branch", "-D", branch)

	var stdout, stderr bytes.Buffer
	if err := CreateManifests(context.Background(), createManifestFixtureOptions(t, f, &stdout, &stderr)); err != nil {
		t.Fatalf("second CreateManifests: %v\nstderr: %s", err, stderr.String())
	}
	if !strings.Contains(stdout.String(), "all manifest files already exist; nothing created") {
		t.Errorf("no-op result = %q", stdout.String())
	}
}

func TestCreateManifestsRefusesAnExistingDifferentFile(t *testing.T) {
	f := newInitFixture(t)
	rel := "domains/sales/distribution/host/component.yaml"
	gittest.Commit(t, f.gitopsOrigin, rel, "hand-written: true\n", "add hand-written manifest")

	var stdout, stderr bytes.Buffer
	err := CreateManifests(context.Background(), createManifestFixtureOptions(t, f, &stdout, &stderr))
	if err == nil {
		t.Fatal("expected a create-only conflict")
	}
	for _, want := range []string{"already exist and differ", rel, "never replaces"} {
		if !strings.Contains(err.Error(), want) {
			t.Errorf("error %q does not contain %q", err, want)
		}
	}
	branches := gittest.Run(t, f.gitopsOrigin, "branch", "--list")
	if strings.Contains(branches, "manifests-create/") {
		t.Errorf("a conflicting create published a review branch: %s", branches)
	}
}

func TestCreateManifestsDryRunCreatesNoReviewBranch(t *testing.T) {
	f := newInitFixture(t)
	var stdout, stderr bytes.Buffer
	opts := createManifestFixtureOptions(t, f, &stdout, &stderr)
	opts.DryRun = true
	if err := CreateManifests(context.Background(), opts); err != nil {
		t.Fatalf("CreateManifests --dry-run: %v", err)
	}
	if !strings.Contains(stdout.String(), "nothing created (--dry-run)") {
		t.Errorf("dry-run result = %q", stdout.String())
	}
	branches := gittest.Run(t, f.gitopsOrigin, "branch", "--list")
	if strings.Contains(branches, "manifests-create/") {
		t.Errorf("dry-run created a review branch: %s", branches)
	}
}

func TestCreateManifestsDiffReportsConflictWithoutWriting(t *testing.T) {
	f := newInitFixture(t)
	rel := "domains/sales/distribution/host/component.yaml"
	gittest.Commit(t, f.gitopsOrigin, rel, "hand-written: true\n", "add hand-written manifest")

	var stdout, stderr bytes.Buffer
	opts := createManifestFixtureOptions(t, f, &stdout, &stderr)
	opts.Diff = true
	if err := CreateManifests(context.Background(), opts); err != nil {
		t.Fatalf("CreateManifests --diff: %v", err)
	}
	for _, want := range []string{rel + " (current)", rel + " (generated)"} {
		if !strings.Contains(stdout.String(), want) {
			t.Errorf("diff does not contain %q:\n%s", want, stdout.String())
		}
	}
}
